# Generated by Django 4.0.1 on 2022-01-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='logo',
            field=models.CharField(blank=True, max_length=250, verbose_name='Ссылка на логотип компании'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary',
            field=models.CharField(blank=True, max_length=250, verbose_name='Зарплата'),
        ),
    ]
