# Generated by Django 4.0.1 on 2022-01-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_alter_vacancy_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='logo',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ссылка на логотип компании'),
        ),
    ]
