# Generated by Django 4.0.1 on 2022-01-29 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0005_alter_vacancy_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='salary',
        ),
    ]
