# Generated by Django 4.0.1 on 2022-01-29 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0006_remove_vacancy_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='logo',
        ),
    ]
